# Generated by Django 5.2 on 2025-04-29 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0001_initial'),
        ('salons', '0004_alter_salon_owner_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='salon',
            field=models.ForeignKey(blank=True, help_text='Optional salon for stylist registrations', null=True, on_delete=django.db.models.deletion.CASCADE, to='salons.salon'),
        ),
    ]
