#version: '3.8'

services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      # - redis  # Commented out for Render deployment


  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: yosephman@gmail.com
      PGADMIN_DEFAULT_PASSWORD: SuperSecret1234
    ports:
      - "5050:80"               # Expose pgAdmin on http://localhost:5050
    depends_on:
      - db

  # redis:  # Commented out for Render deployment
  #   image: redis:7-alpine
  #   # we don't need to expose to host:
  #   # ports: []

volumes:
  postgres_data:
