# Generated by Django 5.2 on 2025-04-25 05:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='stylists',
            field=models.ManyToManyField(blank=True, help_text='Approved stylists working at this salon', limit_choices_to={'role': 'STYLIST'}, related_name='salons', to=settings.AUTH_USER_MODEL),
        ),
    ]
